# Use Python base image
FROM python:3.9-slim

# Set working directory
WORKDIR /app

# Copy forwarder files
COPY forwarder.py ./

# Expose port
EXPOSE 9000/udp

# Run the forwarder
CMD ["python", "forwarder.py"]